### ISSUE TITLE
Hurty code moment

### ISSUE THREAD

**Issue by RedBrumbler** [JD-The-65th/launchQuotes#1]
[this code](https://github.com/Jd-Gamer65/launchQuotes/blob/86db02513be4cca45b57c38649aeda14932e0835/src/Hooks/MainMenuViewController.cpp#L53-L230) kind of hurts to look at, may I recommend putting all of these in an array or vector and using the random int to index into that array or vector? example:

```c++
std::vector<std::string> quotes = {
    "quote 1",
    "quote 2"
};

std::string get_quote()
{
    int randomInt = rand() % quotes.size();
    return quotes[randomInt];
}
```

This would make your code more performant

**Comment by RedBrumbler** [comment]
and might I add, it would make adding new quotes easier since less edits

**Comment by RedBrumbler** [comment]
if you're wondering why it hurts, it's because all the if statements always run, meaning that it needs to evaluate all 58 possibilities every time it runs through that method. this would already be better with a switch case or else if ladder, but really this is a job for a vector or array to be indexed into. 

This also means that making a file that contains these splash texts is going to be easier when it just reads from a vector, because then you can have a file on the quest that you read and split based on a character, meaning people can add their own quotes if they want to

**Comment by JD-The-65th** [comment]
Alright, working on implementing this near 4:00 PM EST today

**Comment by JD-The-65th** [comment]
Fixed in [This Commit](https://github.com/Jd-Gamer65/launchQuotes/commit/18cd76743482a89e8eaa585d1bfea8e1a9eb971e)
